ECHO=@

generate:
	$(ECHO) $(MAKE) -C icons
	$(ECHO) $(MAKE) -C schema-validator
	$(ECHO) $(MAKE) -C monaco

clean:
	@echo Cleaning
	$(ECHO) $(MAKE) -C icons clean
	$(ECHO) $(MAKE) -C schema-validator clean
	$(ECHO) $(MAKE) -C monaco clean
