# This is a JSON Type Definition
# https://jsontypedef.com/docs/jtd-in-5-minutes/
optionalProperties:
  formats:
    elements:
      properties:
        name:
          type: string
        template:
          type: string
      optionalProperties:
        joinString:
          type: string
        contextMenu:
          type: boolean
  remoteRules:
    elements:
      type: string
  urlRules:
    elements:
      properties:
        urlPattern:
          type: string
        rules:
          elements:
            properties:
              field:
                enum:
                  - title
                  - url
              match:
                type: string
            optionalProperties:
              replacement:
                type: string
