formats:
  - name: HTML
    template: '<a href="{{url}}">{{title}}<a>{{#suffix}}: "{{.}}"{{/suffix}}'
    joinString: <br>
    contextMenu: false
  - name: text
    template: |
      {{{title}}}{{#suffix}}: "{{{.}}}"{{/suffix}}
      {{{url}}}
    contextMenu: false
  - name: Markdown
    template: '[{{{title}}}]({{{url}}}){{#suffix}}: "{{{.}}}"{{/suffix}}'
  - name: Asciidoc
    template: 'link:{{{url}}}({{{title}}}){{#suffix}}: "{{{.}}}"{{/suffix}}'
remoteRules: []
  # See https://www.jsdelivr.com/?docs=gh
  # - https://cdn.jsdelivr.net/gh/user/proj/copyTabTitleAndURL-rules.json
urlRules:
  - urlPattern: https://docs.google.com/document/d/*
    rules:
      # Google docs titles always end with ' - Google Docs'
      - field: title
        match: ' - Google Docs$'
        replacement: ""
  - urlPattern: https://github.com/*/*/issues/*
    rules:
      # Turn "Some Title 路 Issue #1234 路 user/proj"
      # Into "user/proj #1234: Some Title"
      # and store Some Title as field 'suffix'
      # (we'll also create fields _issue_number and _project but discard them because of the leading '_')
      - field: title
        match: '^(?<suffix>.+) 路 Issue #(?<_issue_number>\d+) 路 (?<_project>.+)$'
        replacement: '$<_project> #$<_issue_number>'
